name: 'System.out.println("Hello, World")'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.06391
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#11110d'
    - '#22211b'
    - '#333333'
    - '#4f4e4d'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
