name: 'System.out.println("Hello, World")'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.06391
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9666368891485035
  lightness: 0.2993117617443204
  saturation: 0.39939240203239024
  rhythmicContrast: 0.01897282642312348
purpose: []
